resolver: lts-11.3
extra-deps:
- invertible-hxt-0.1
- HUnit-1.3.1.2
- ansi-terminal-0.6.3.1
packages:
- location: .
- location:
    git: git://github.com/dylex/HUnit-Diff
    commit: 88a2695
  extra-dep: true
